apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-je3b
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-bpkv-tenant/status-quarkus-io/statusquarkusio-je3b@sha256:9aef5feece954a3585963ae9331d014981b570f5809040de25f68400e1e64099
        name: my-java-quarkus
        resources: {}
status: {}
