apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-je3b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-je3b
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-je3b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-je3b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-je3b
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-bpkv-tenant/status-quarkus-io/statusquarkusio-je3b@sha256:9aef5feece954a3585963ae9331d014981b570f5809040de25f68400e1e64099
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
